analytics: {}
color:
  brandColors:
    - '#A8D8D8'
    - '#300800'
    - '#000000'
    - '#F09820'
    - '#F0E880'
  brandStrength: 0.337837
  lightness: 0.322072
  rhythmicContrast: 0.359234
  saturation: 0.306306
cta: {}
layout_spectrum: 1
name: CristalBernardi
opengraph: {}
purpose: {}
typography_spectrum: 0.281531
