name: CristalBernardi
favicon: null
layout_spectrum: 0.45572
typography_spectrum: 0.93678
title: 'Amor '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#767bb2'
    - '#ec6699'
    - '#7acfd4'
    - '#f9cede'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
