name: CristalBernardi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.281531
title: 'Amor '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A8D8D8'
    - '#300800'
    - '#000000'
    - '#F09820'
    - '#F0E880'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
